In [1]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.33.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer, Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
from datasets import load_dataset, Dataset
from peft import get_peft_model, LoraConfig, TaskType, PeftModel
import torch

In [ ]:
!unzip mbart_lora_es_pt.zip -d mbart_lora_es_pt

In [3]:
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM,
)

In [4]:
model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
model     = M2M100ForConditionalGeneration.from_pretrained(model_name)
model = get_peft_model(model, peft_config)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [5]:
import huggingface_hub
huggingface_hub.login() # now you will be prompted to enter your token; enter it.

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [6]:
ds_es = load_dataset("openlanguagedata/flores_plus", "spa_Latn", split="dev")
ds_pt = load_dataset("openlanguagedata/flores_plus", "por_Latn", split="dev")
parallel_pt = [{"translation": {"es": e["text"], "pt": p["text"]}} for e, p in zip(ds_es, ds_pt)]

README.md:   0%|          | 0.00/72.5k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

spa_Latn.parquet:   0%|          | 0.00/129k [00:00<?, ?B/s]

spa_Latn.parquet:   0%|          | 0.00/134k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

por_Latn.parquet:   0%|          | 0.00/122k [00:00<?, ?B/s]

por_Latn.parquet:   0%|          | 0.00/127k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [7]:
dataset_pt = Dataset.from_list(parallel_pt).train_test_split(test_size=0.1, seed=42)
train_pt = dataset_pt["train"]
eval_pt = dataset_pt["test"]

In [10]:
tokenizer.src_lang = "es"

def tokenize_es_pt(batch):
    # batch['translation'] es un dict {"es": ..., "pt": ...}
    src_texts = [ex["es"] for ex in batch["translation"]]
    tgt_texts = [ex["pt"] for ex in batch["translation"]]

    # ← idioma origen ya se indicó una sola vez con tokenizer.src_lang = "es"
    model_inputs = tokenizer(
        src_texts,
        max_length=128,
        padding="max_length",
        truncation=True
    )

    # Idioma destino solo se pone al tokenizar los labels
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            tgt_texts,
            max_length=128,
            padding="max_length",
            truncation=True
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_tokenized_pt = train_pt.map(tokenize_es_pt, batched=True, remove_columns=train_pt.column_names)
eval_tokenized_pt  = eval_pt.map(tokenize_es_pt,  batched=True, remove_columns=eval_pt.column_names)

Map:   0%|          | 0/897 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [11]:
training_args_pt = Seq2SeqTrainingArguments(
    output_dir="./mbart_lora_es_pt",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=5e-4,
    num_train_epochs=15,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs_pt",
    predict_with_generate=True,  # Importante para traducción
    fp16=torch.cuda.is_available(),  # Entrenamiento más rápido si tienes GPU
    save_total_limit=1,
    report_to="none",
    label_names=["labels"]
)

trainer_pt = Seq2SeqTrainer(
    model=model,
    args=training_args_pt,
    train_dataset=train_tokenized_pt,
    eval_dataset=eval_tokenized_pt,
    processing_class=tokenizer,
    data_collator=DataCollatorForSeq2Seq(tokenizer, model=model),
)

In [12]:
trainer_pt.train()

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

TrainOutput(global_step=3375, training_loss=5.491941912615741, metrics={'train_runtime': 446.2331, 'train_samples_per_second': 30.152, 'train_steps_per_second': 7.563, 'total_flos': 3656988874506240.0, 'train_loss': 5.491941912615741, 'epoch': 15.0})

In [13]:
model.save_pretrained("./mbart_lora_es_pt")
tokenizer.save_pretrained("./mbart_lora_es_pt")
print("✅ Adaptadores LoRA para Español → Portugués guardados.")

✅ Adaptadores LoRA para Español → Portugués guardados.

In [29]:
model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
base_model     = M2M100ForConditionalGeneration.from_pretrained(model_name)
model = PeftModel.from_pretrained(base_model, "./mbart_lora_es_pt")

In [30]:
model.train()
for name, param in model.named_parameters():
    if "lora" in name:
        param.requires_grad = True

model.print_trainable_parameters()

trainable params: 1,179,648 || all params: 485,085,184 || trainable%: 0.2432

In [31]:
ds_gl = load_dataset("openlanguagedata/flores_plus", "glg_Latn", split="dev")
parallel_gl = [{"translation": {"es": e["text"], "gl": g["text"]}} for e, g in zip(ds_es, ds_gl)]

dataset_gl = Dataset.from_list(parallel_gl).train_test_split(test_size=0.1, seed=42)
train_gl = dataset_gl["train"]
eval_gl = dataset_gl["test"]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

In [33]:
# 1 · Idioma de origen (solo una vez)
tokenizer.src_lang = "es"        # español
tokenizer.tgt_lang = "gl"      # destino  ← ¡ESTO faltaba!

# 2 · Función de tokenización es → gl
def tokenize_es_gl(batch):
    src_texts = [ex["es"] for ex in batch["translation"]]
    tgt_texts = [ex["gl"] for ex in batch["translation"]]

    # Entrada
    model_inputs = tokenizer(
        src_texts,
        max_length=128,
        padding="max_length",
        truncation=True,
    )

    # Etiquetas (lengua destino)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            tgt_texts,
            max_length=128,
            padding="max_length",
            truncation=True,
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# 3 · Mapeo sobre tus splits
train_tokenized_gl = train_gl.map(tokenize_es_gl, batched=True,
                                  remove_columns=train_gl.column_names)
eval_tokenized_gl  = eval_gl.map(tokenize_es_gl,  batched=True,
                                  remove_columns=eval_gl.column_names)

Map:   0%|          | 0/45 [00:00<?, ? examples/s]

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

In [34]:
training_args_gl = Seq2SeqTrainingArguments(
    output_dir="./mbart_lora_es_gl",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    learning_rate=5e-4,
    num_train_epochs=15,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs_gl",
    predict_with_generate=True,
    fp16=torch.cuda.is_available(),
    save_total_limit=1,
    report_to="none",
    label_names=["labels"]
)

trainer_gl = Seq2SeqTrainer(
    model=model,
    args=training_args_gl,
    train_dataset=train_tokenized_gl,
    eval_dataset=eval_tokenized_gl,
    processing_class=tokenizer,
    data_collator=DataCollatorForSeq2Seq(tokenizer, model=model),
)

In [35]:
trainer_gl.train()

('./mbart_lora_es_gl/tokenizer_config.json',
 './mbart_lora_es_gl/special_tokens_map.json',
 'mbart_lora_es_gl/vocab.json',
 'mbart_lora_es_gl/sentencepiece.bpe.model',
 './mbart_lora_es_gl/added_tokens.json')

In [43]:
model.save_pretrained("./m2m100_lora_es_gl")
tokenizer.save_pretrained("./m2m100_lora_es_gl")

('./m2m100_lora_es_gl/tokenizer_config.json',
 './m2m100_lora_es_gl/special_tokens_map.json',
 'm2m100_lora_es_gl/vocab.json',
 'm2m100_lora_es_gl/sentencepiece.bpe.model',
 './m2m100_lora_es_gl/added_tokens.json')

In [36]:
pip install evaluate sacrebleu

Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.4)
Requirement already satisfied: sacrebleu in /usr/local/lib/python3.11/dist-packages (2.5.1)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.33.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: portalocker in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (3.2.0)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (0.4.6)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (5.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.11.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [37]:
from evaluate import load

In [44]:
from typing import List

# ──────────────────────────────────────────────────────────────
#  Función de prueba en lote para es → gl
# ──────────────────────────────────────────────────────────────
def test_translation_batch(
    sentences_es: List[str],
    references_gl: List[str],
    model_path: str = "./m2m100_lora_es_gl",
):
    try:
        # 1 · Modelo base + adaptador LoRA
        base = "facebook/m2m100_418M"            # checkpoint multilingüe
        base_model = M2M100ForConditionalGeneration.from_pretrained(base)
        model      = PeftModel.from_pretrained(base_model, model_path)
        model.eval()

        device = "cuda" if torch.cuda.is_available() else "cpu"
        model.to(device)

        # 2 · Tokenizador
        tokenizer = M2M100Tokenizer.from_pretrained(base)   # o model_path si copiaste el vocabulario
        tokenizer.src_lang = "es"                           # idioma de entrada

        # 3 · Preparar lote de entradas
        inputs = tokenizer(
            sentences_es,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=128,
        ).to(device)

        # 4 · Generar traducciones (forzamos <gl>)
        gl_bos_id = tokenizer.get_lang_id("gl")
        with torch.no_grad():
            generated = model.generate(
                **inputs,
                forced_bos_token_id=gl_bos_id,
                max_length=128,
                num_beams=4,
                early_stopping=True,
            )

        translations = tokenizer.batch_decode(generated, skip_special_tokens=True)

        # 5 · Mostrar pares
        for src, pred, ref in zip(sentences_es, translations, references_gl):
            print(f"ES: {src}")
            print(f"GL (pred): {pred}")
            print(f"GL (ref) : {ref}")
            print("-" * 60)

        # 6 · Métricas BLEU y chrF
        bleu = load("bleu")
        chrf = load("chrf")

        bleu_score = bleu.compute(
            predictions=translations,
            references=[[r] for r in references_gl],
        )
        chrf_score = chrf.compute(
            predictions=translations,
            references=references_gl,
        )

        print("\n📊 Métricas globales:")
        print(f"BLEU : {bleu_score['bleu']:.4f}")
        print(f"chrF : {chrf_score['score']:.2f}")

    except Exception as e:
        print(f"❌ Error en traducción: {e}")

In [45]:
ds_es = load_dataset("openlanguagedata/flores_plus", "spa_Latn", split="devtest[:50]")
ds_gl = load_dataset("openlanguagedata/flores_plus", "glg_Latn", split="devtest[:50]")

# Tomar una muestra de 50 ejemplos para visualización
sample_es = ds_es["text"][:50]
sample_gl = ds_gl["text"][:50]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

In [46]:
test_translation_batch(sample_es, sample_gl)

ES: «Actualmente, tenemos ratones de cuatro meses de edad que antes solían ser diabéticos y que ya no lo son», agregó.
GL (pred): O presidente da Cámara de Representantes da ONU, José Manuel Barroso, afirmou:
GL (ref) : "Agora temos ratos de 4 meses que xa non son diabéticos, pero que no seu momento si que o foron", engadiu.
------------------------------------------------------------
ES: La investigación todavía se ubica en su etapa inicial, conforme indicara el Dr. Ehud Ur, docente en la carrera de medicina de la Universidad de Dalhousie, en Halifax, Nueva Escocia, y director del departamento clínico y científico de la Asociación Canadiense de Diabetes.
GL (pred): A investigación aínda está na súa fase inicial, informou o profesor de medicina na Universidade de Dalhousie, en Halifax, Nova Escocia, e o director do departamento clínico e científico da Asociación Canadense de Diabetes.
GL (ref) : O Dr. Ehud Ur, profesor de medicina na Universidade Dalhousie en Halifax (Nova Escocia) e presidente da división clínica e científica da Asociación canadense contra a diabetes advertiu de que a investigación aínda está nunha fase inicial.
------------------------------------------------------------
ES: Al igual que otros especialistas, es escéptico acerca de si la diabetes tiene cura y remarca que estos descubrimientos no son relevantes para quienes que ya padecen de diabetes de tipo 1.
GL (pred): Xunto con outros expertos, el é escéptico sobre a cura do diabetes.
GL (ref) : Do mesmo xeito que outros expertos, amósase escéptico de que a diabetes teña cura e apunta que estes achados non son relevantes para as persoas que xa teñen diabetes de tipo 1.
------------------------------------------------------------
ES: El lunes, Sara Danius, secretaria permanente del Comité por el Nobel de Literatura de la Academia Sueca, declaró públicamente en un programa radiofónico de Sveriges, en Suecia, que, al no poder contactar directamente con Bob Dylan para comunicarle el premio en Literatura 2016, el comité había abandonado sus esfuerzos por comunicarse con él.
GL (pred): O récord do premio Nobel de Literatura da Academia Sueca, Sara Danius, chegou a ser o máis importante do que o da Academia Sueca, e o máis importante do que o da Academia Sueca, Sara Danius, foi o máis importante do que o da Academia Sueca.
GL (ref) : O pasado luns, Sara Danius, a secretaria permanente do Comité do Nobel de Literatura da Academia Sueca, anunciou en público durante unha entrevista no programa de radio da cadea Sveriges Radio en Suecia que o comité, ao non lograr contactar directamente con Bob Dylan acerca do outorgamento do Premio Nobel de Literatura 2016, decidira abandonar os intentos de falar con el.
------------------------------------------------------------
ES: Danius declaró: «Actualmente no estamos haciendo nada. Llamé y envié correos electrónicos a su asistente más cercano y recibí contestaciones muy cordiales. Por el momento, eso es sin dudas suficiente».
GL (pred): Danius dixo: "Actualmente non facemos nada. Chamou, enviou un correo electrónico ao seu asistente máis próximo e recibiu respostas moi cordiais.
GL (ref) : Danius afirmou: «Agora mesmo non estamos a facer nada. Chamei e envieille correos electrónicos ao seu colaborador máis próximo e recibín respostas moi amables. De momento, con iso abonda».
------------------------------------------------------------
ES: Con anterioridad, el director ejecutivo de Ring, Jamie Siminoff, mencionó que la compañía había iniciado a raíz de que el timbre de su entrada no podía oírse desde la tienda que tenía montada en su garaje.
GL (pred): Xusto antes, o director xeral de Ring, Jamie Siminoff, informou de que a compañía comezou co fin de que a tempada do seu ingreso puidese escoitar desde o barco que estaba instalado no seu garaxe.
GL (ref) : Previamente, o director executivo de Ring, Jamie Siminoff, destacou que a empresa naceu cando non puido oír o timbre da porta desde o seu taller no garaxe.
------------------------------------------------------------
ES: Él dijo que construyó un timbre wifi.
GL (pred): Algunhas das razóns máis importantes son as de que, polo tanto, o sistema de seguridade de seguridade e seguridade dos servizos de seguridade e de seguridade dos servizos de seguridade e de seguridade dos servizos de seguridade.
GL (ref) : Afirmou que construíu un timbre wifi.
------------------------------------------------------------
ES: Siminoff declaró que las ventas se dispararon luego de su aparición en un episodio de Shark Tank en el año 2013, en el que el panel del programa televisivo se negó a financiar la puesta en marcha de la compañía.
GL (pred): Xusto despois das 11:30 h, a policía de Nova Zelandia anunciou que a policía de Nova Zelandia, a policía de Nova Zelandia e a policía de Nova Zelandia, a policía de Nova Zelandia e a policía de Nova Zelandia, a policía de Nova Zelandia e a policía de Nova Zelandia, a policía de Nova Zelandia, a policía de Nova Zelandia e a policía de Nova Zelandia, a policía de Nova Zelandia e a policía de Nova Zelandia
GL (ref) : Siminoff afirmou que as vendas se incrementaron despois da súa aparición en 2013 no episodio Shark Tank, no que o panel do programa rexeitou financiar a empresa emerxente.
------------------------------------------------------------
ES: Hacia fines del año 2017, Siminoff hizo una aparición en el canal de compras televisadas QVC.
GL (pred): Xusto despois das 11:30 h, Siminoff púxose no canal de compras QVC no final do ano.
GL (ref) : Foi a finais de 2017 cando Siminoff apareceu na canle de compras por televisión QVC.
------------------------------------------------------------
ES: Ring también llegó a un acuerdo en el litigio con la compañía de seguridad de la competencia, ADT Corporation.
GL (pred): Rings tamén chegou a un acordo no que se disputou co equipo de seguridade da competición, ADT Corporation.
GL (ref) : Ring tamén chegou a un acordo extraxudicial cunha empresa de seguridade competidora, a ADT Corporation.
------------------------------------------------------------
ES: Al día de hoy no se ha demostrado a ciencia cierta que algún fármaco sea adecuado para tratar la infección existente causada por ébola, aun cuando existe una vacuna experimental que pareciera ser capaz de disminuir la mortalidad causada por esa enfermedad.
GL (pred): Aínda que a epidemia de epidemia de Ebola se produza, a epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia de epidemia diurnos de U.S.A.
GL (ref) : Aínda que os indicios apuntan a que unha vacina experimental é capaz de reducir a mortalidade causada polo ébola, ata o momento, ningún medicamento demostrou de xeito evidente a súa capacidade para tratar esa infección.
------------------------------------------------------------
ES: Zmapp, un combinado de anticuerpos, tuvo un prometedor resultado de campo al principio, pero estudios los formales demostraron que era menos beneficioso de lo que se esperaba para prevenir la muerte.
GL (pred): O récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de récord de volumen de récord de récord de volumen vol vol vol vol vol vol vol vol vol vol vol vol vol vol vol vol vol vol vol vol
GL (ref) : Un cóctel de anticorpos, o ZMapp, presentou nun principio resultados prometedores nese campo, pero outros estudos formais apuntaron a que presentaba menos beneficios dos esperados na prevención da mortalidade.
------------------------------------------------------------
ES: En el ensayo PALM, la función de Zmapp fue de control, es decir, que los científicos lo utilizaron como base y compararon con él los otros tres tratamientos.
GL (pred): O récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord do récord dos récord do récord do récord do récord dos récord dos récord dos récord dos récords de U.
GL (ref) : No xuízo contra PALM, ZMapp actuou como control, é dicir, os científicos empregárono como liña base e compararon tres outros medicamentos con el.
------------------------------------------------------------
ES: USA Gymnastics respalda la nota del Comité Olímpico de los Estados Unidos y reconoce que resulta imperioso que la familia olímpica fomente un entorno seguro para todos nuestros deportistas.
GL (pred): O comité olímpico dos Estados Unidos (CEDAW) informou que o comité olímpico dos Estados Unidos (CEDAW) chegou ao seu lugar.
GL (ref) : USA Gymnastics apoia a carta do Comité Olímpico dos EE. UU. e acepta a imperiosa necesidade de que a familia olímpica fomente unha contorna segura para todas as atletas.
------------------------------------------------------------
ES: Coincidimos con la declaración de la USOC de que los intereses de los atletas, los clubes y sus deportes, pueden ser atendidos más apropiadamente si se avanza con cambios significativos dentro de nuestra organización, en lugar del retiro de las certificaciones.
GL (pred): Despois do ataque, o ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque ao ataque.
GL (ref) : Concordamos coa declaración do USOC que afirma que os intereses dos nosos atletas e clubs, e do seu deporte, poderían estar mellor atendidos pensando no futuro cun cambio significativo dentro na nosa organización, en lugar da retirada da certificación.
------------------------------------------------------------
ES: USA Gymnastics respalda a una investigación independiente que puede esclarecer de qué modo el abuso de la proporción que los sobrevivientes de Larry Nassa describieron con tanto coraje pudo haber pasado sin ser visto por tanto tiempo y acepta cualquier cambio necesario y adecuado.
GL (pred): Os medios de comunicación estadounidenses axudaron a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a axudar a loitar contra o problema.
GL (ref) : USA Gymnastics apoia unha investigación independente que podería aclarar como uns abusos das dimensións descritas con tanta coraxe polas superviventes de Larry Nassar puideron pasar desapercibidas durante tanto tempo e acolle todos os cambios necesarios e apropiados.
------------------------------------------------------------
ES: La meta de USA Gymnastics y USOC es la misma: lograr que la gimnasia y otros deportes sean lo más seguro posible para que los atletas persigan sus sueños en un entorno protegido, positivo y potenciado.
GL (pred): Os obxectivos dos US Gymnastics e dos USOC son os mesmos: facer máis seguros o máximo posible para que os atletas poñan os seus soños nun ambiente protexido, positivo e reforzado.
GL (ref) : O USA Gymnastics e o USOC teñen o mesmo obxectivo: facer que a ximnasia como deporte, así como outros máis, sexan o máis seguros posible para que as atletas poidan seguir os seus soños nunha contorna segura, positiva e empoderada.
------------------------------------------------------------
ES: Durante los años 60, Brzezinski trabajó para John F. Kennedy en el puesto de asesor y, posteriormente, para el gobierno de Lyndon B. Johnson.
GL (pred): Brzezinski traballou no cargo de conselleiro de John F. Kennedy e o goberno de Lyndon B. Johnson no ano 1960.
GL (ref) : Foi ao longo da década dos 60 cando Brzezinski traballou para John F. Kennedy en calidade de asesor e, deseguido, para a administración de Lyndon B. Johnson.
------------------------------------------------------------
ES: Asesoró a Carter en materia de política exterior en las elecciones de 1976. Posteriormente, trabajó como asesor de seguridad nacional (ASN) entre 1977 y 1981, luego de Henry Kissinger.
GL (pred): Xusto despois das eleccións de 1976, Carter foi o conselleiro de seguridade nacional (ASN) despois de Henry Kissinger.
GL (ref) : Durante as eleccións de 1976, asesorou a Carter sobre política exterior e, posteriormente, traballou como Asesor de Seguridade Nacional (NSA) entre 1977 e 1981, como sucesor de Henry Kissinger.
------------------------------------------------------------
ES: Como consejero de seguridad nacional, asistió a Carter en el manejo diplomático de asuntos internacionales, como los Acuerdos de Camp David de 1978, la normalización de las relaciones entre Estados Unidos y China a fines de la década de 1970, la Revolución iraní de 1979, la que llevó a una crisis de rehenes en Irán, y la invasión soviética en Afganistán, en 1979.
GL (pred): Nado en Afganistán, Carter foi o primeiro ministro das forzas de seguridade e de seguridade do país, e foi o primeiro ministro das forzas de seguridade.
GL (ref) : Na Axencia Nacional de Seguridade, asistiu a Carter na xestión diplomática de temas internacionais, como os Acordos de Camp David, en 1978; a normalización das relacións entre EE. UU. e China ata finais dos anos 70; a revolución iraniana, que desencadeou a crise dos reféns iranianos, en 1979; e a invasión soviética de Afganistán, en 1979.
------------------------------------------------------------
ES: El filme, protagonizado por Tyan Gosling y Emma Stone, fue nominado en todas las categorías más importantes.
GL (pred): A película, protagonizada por Tyan Gosling e Emma Stone, foi nomeada en todas as categorías máis importantes.
GL (ref) : A película, cos actores Ryan Gosling e Emma Stone, foi nominada en todas as principais categorías.
------------------------------------------------------------
ES: Gosling y Stone fueron nominados como Mejor Actor y Mejor Actriz, respectivamente.
GL (pred): Cada vez máis, o actor e a actriz foron nomeados como o mellor actor e o mellor actor.
GL (ref) : Gosling e Stone recibiron nominacións a Mellor Actor e Actriz, respectivamente.
------------------------------------------------------------
ES: Entre las demás nominaciones se encuentran Mejor película, Mejor director, Mejor cinematografía, Mejor diseño de vestuario, Mejor edición de películas, Mejor partitura original, Mejor diseño de producción, Mejor edición de sonido, Mejor mezcla de sonido y Mejor guion original.
GL (pred): A pesar das acusacións máis importantes, a película comezou a ser máis popular, co fin de aumentar a produción, a produción, a produción e a produción.
GL (ref) : Outras nominacións tamén incluíron Mellor película, Mellor director, Mellor cinematografía, Mellor deseño de vestiario, Mellor edición, Mellor banda sonora orixinal, Mellor deseño de produción, Mellor edición de son, Mellor mestura de son e Mellor guión orixinal.
------------------------------------------------------------
ES: Fueron dos las nominadas a mejor canción original: Audición (Los tontos que sueñan) y Ciudad de estrellas. El estudio Lionsgate fue nominado 26 veces, superando a cualquier otro estudio.
GL (pred): Nomeouse a mellor canción orixinal: Audición (Os tolos que soñan) e Cidade de estrelas. O estudo Lionsgate foi nomeado 26 veces, superando a calquera outro estudio.
GL (ref) : Dúas cancións da película, Audition (The Fools Who Dream) e City of Stars, foron nominadas a mellor canción orixinal. O estudio Lionsgate recibiu 26 nominacións: máis ca ningún outro estudio.
------------------------------------------------------------
ES: El domingo por la noche, en un anuncio realizado mediante el secretario de prensa, el presidente de los Estados Unidos de América, Donald Trump, comunicó que las tropas estadounidenses se retirarían de Siria.
GL (pred): Trump, o presidente dos Estados Unidos de América, informou de que as tropas dos Estados Unidos retiraranse da Siria no día 10 de outubro.
GL (ref) : A última hora do domingo, o presidente dos EE. UU., Donald Trump, anunciou a través dunha declaración emitida polo secretario de prensa que as tropas estadounidenses ían abandonar Siria.
------------------------------------------------------------
ES: El anuncio se hizo tras la conversación telefónica que Trump mantuvo con con el presidente de Turquía, Recep Tayyip Erdoğan.
GL (pred): A declaración fíxose despois dunha conversa telefónica co presidente de Turquía, Recep Tayyip Erdoğan.
GL (ref) : Este anuncio realizouse despois de que Trump falase por teléfono co presidente turco Recep Tayyip Erdoğan.
------------------------------------------------------------
ES: Turquía asumiría, además, la vigilancia de los militantes del ISIS que fueron capturados, a quienes las naciones europeas, conforme indica el comunicado, les denegó su repatriación.
GL (pred): O récord da guerra contra o terrorismo, o terrorismo e o terrorismo, chegou a ser o punto máis alto en Turquía.
GL (ref) : Turquía tamén se encargaría da custodia dos soldados do EIIL que, segundo a declaración, os países europeos rexeitaron repatriar.
------------------------------------------------------------
ES: Además de confirmar que al menos algunos dinosaurios eran plumíferos, una teoría ya generalizada, también ofrece datos específicos que los fósiles por lo general no ofrecen, como su color y su estructura tridimensional.
GL (pred): Ademais de confirmar que ao menos algúns dinosaurios eran plumíferos, a teoría xa é popular, tamén ofrece datos específicos que os fósiles xeralmente non ofrecen, incluíndo a cor e a estrutura tridimensional.
GL (ref) : Isto confirma que como mínimo algúns dinosauros tiñan plumas (unha teoría xa estendida) e ademais proporciona outros datos que, polo xeral, os fósiles non nos ofrecen, como poden ser a cor e a disposición tridimensional.
------------------------------------------------------------
ES: Según los especialistas, este animal tiene un plumaje de color castaño en la zona superior y una tonalidad pálida o carotenoide en la parte de abajo.
GL (pred): Os investigadores afirmaron que o canteiro tiña unha cor de castaño na parte superior e unha tonalidade pálida ou carotenoide na parte inferior.
GL (ref) : . Os científicos afirman que as plumas do animal eran de cor castaña na parte superior e na parte inferior pálidas ou de cor carotenoide.
------------------------------------------------------------
ES: Asimismo, el hallazgo permite comprender mejor la evolución de las plumas de las aves.
GL (pred): Despois da tempada, os bombeiros chegaron a descubrir o que era a tempada das aves.
GL (ref) : O achado tamén ofrece unha perspectiva sobre como evolucionaron as plumas nos paxaros.
------------------------------------------------------------
ES: Dado que el plumaje de los dinosaurios no tiene un eje bien desarrollado, denominado raquis, pero sí presenta otros rasgos de las plumas (cerdas y bárbulas), los investigadores llegaron a la conclusión de que es probable que el raquis sea el resultado de un desarrollo evolutivo posterior de estas otras características.
GL (pred): O presbítero dos presbíteros non tiña un eixe ben desenvolvido, chamado raquis, pero tiña outras características das prendas (cerdas e bárbulas), e os investigadores concluíron que o raquis probablemente resultou dun desenvolvemento evolutivo posterior destas outras características.
GL (ref) : Como as plumas dos dinosauros non teñen un canón ben desenvolvido, chamado raquis, pero si outras características propias das plumas (barbas e bárbulas), os investigadores deduciron que o raquis probablemente represente unha evolución posterior a esas outras características.
------------------------------------------------------------

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

📊 Métricas globales:
BLEU : 0.0893
chrF : 32.20